package suike.suikecherry;

import suike.suikecherry.asm.*;
import suike.suikecherry.item.*;
import suike.suikecherry.data.*;
import suike.suikecherry.block.*;
import suike.suikecherry.expand.*;
import suike.suikecherry.config.*;
import suike.suikecherry.world.biome.Biomes;
import suike.suikecherry.world.gen.structure.*;
import suike.suikecherry.proxy.CommonProxy;
import suike.suikecherry.packet.PacketHandler;
import suike.suikecherry.achievement.ModAdvancements;

import net.minecraft.client.Minecraft;
import net.minecraft.server.MinecraftServer;

import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.fml.common.SidedProxy;
import net.minecraftforge.fml.common.FMLCommonHandler;
import net.minecraftforge.fml.common.event.FMLConstructionEvent;
import net.minecraftforge.fml.common.event.FMLInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPreInitializationEvent;
import net.minecraftforge.fml.common.event.FMLPostInitializationEvent;
import net.minecraftforge.fml.common.event.FMLServerStartingEvent;

import org.apache.logging.log4j.Logger;

@Mod(
    modid = SuiKe.MODID, name = SuiKe.NAME, version = SuiKe.VERSION,
    guiFactory = "suike.suikecherry.config.gui.GuiFactory"
)
public class SuiKe {

    public static final String MODID = "suikecherry";
    public static final String NAME = "Cherry";
    public static final String VERSION = "1.3.31"; /// 已更新1.3.30

    // public static Logger LOGGER;

    // seed  -2876294365094324906
    // seed  -273158384
    // pos   /tp -1299 102 222
    //       -6 18
    // /give @s minecraft:golden_chestplate 1 0 {Pattern:"flow",Material:"diamond"}
    // /give @s futuremc:netherite_chestplate 1 0 {Pattern:"flow",Material:"diamond"}
    // /summon minecraft:skeleton ~ ~1 ~ {ArmorItems:[{},{},{id:"futuremc:netherite_chestplate",Count:1b,Damage:0s,tag:{Pattern:"flow",Material:"diamond"}}]}

    public static boolean isServer = true;
    public static boolean isZhCn;

    @Mod.Instance
    public static SuiKe instance;
    public SuiKe() { instance = this; }

    @SidedProxy(
        clientSide = "suike.suikecherry.proxy.ClientProxy",
        serverSide = "suike.suikecherry.proxy.CommonProxy"
    )
    public static CommonProxy proxy;

    static { new ASMCoreMod(); }

    @Mod.EventHandler
    public void Construction(FMLConstructionEvent event) {
        if (FMLCommonHandler.instance().getSide().isClient()) {
            isServer = false;
        }

        /*检查联动模组*/Examine.examine();
        /*获取配置文件位置*/Config.config();
    }

    @Mod.EventHandler
    public static void PreInit(FMLPreInitializationEvent event) {
        // LOGGER = event.getModLog();
        LootTableData.registerLootTable();
        proxy.addRegisterTextures();

        if (!isServer) {
            String language = Minecraft.getMinecraft().getLanguageManager().getCurrentLanguage().getLanguageCode();
            isZhCn = (language.equals("zh_cn") || language.equals("zh_tw") || language.equals("zh_hk"));

            模组简介(event);
        }

        /*读取配置文件*/Config.configRead();
    }

    @Mod.EventHandler
    public static void PostInit(FMLPostInitializationEvent event) {
        proxy.register();

        /*执行联动*/Expand.expand();
        /*方块燃烧*/BlockBase.setBlockFire();

        /*初始化附魔书附魔*/EnchData.initEnchantment();
        /*初始化宝藏列表*/TreasureData.Structure.initAll();

        // 注册结构
        ModStructure.registerStructure();

        // 注册生物群系
        Biomes.register();

        // 初始化物品栏
        if (!isServer) {
            ModItemSign.InventoryTabs();
            ModItemBrush.InventoryTabs();
        }

        /*修改forge配置*/net.minecraftforge.common.ForgeModContainer.logCascadingWorldGeneration = false;
    }

    @Mod.EventHandler
    public void onServerStart(FMLServerStartingEvent event) {
        ModAdvancements.registerAll(event.getServer().getAdvancementManager());
        if (!isServer) {
            PacketHandler.registerServerPackets();
        }
    }

// 模组简介
    private static void 模组简介(FMLPreInitializationEvent event) {
        event.getModMetadata().autogenerated = false;
        event.getModMetadata().name = "§e" + NAME;
        event.getModMetadata().url = "";
        event.getModMetadata().updateUrl = "";
        event.getModMetadata().logoFile = "assets/suikecherry/textures/gui/ico.png";

        if (SuiKe.isZhCn) {
            event.getModMetadata().name = "§e樱花";
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§d模组作者: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§e相关链接:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/16834.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/cherry_on_1.12.2" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/cherry-on-1-12-2" + "\n"
                    + "--------------------------------------------------" + "\n"
            ;
        } else {
            event.getModMetadata().name = "§eCherry";
            event.getModMetadata().credits = "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§dMod author: sui_ke" + "\n"
                    + "--------------------------------------------------" + "\n"
                    + "§eRelated links:" + "\n"
                    + "§3MC百科: https://www.mcmod.cn/class/16834.html" + "\n"
                    + "§aModrinth: https://modrinth.com/mod/cherry_on_1.12.2" + "\n"
                    + "§6CurseForge: https://www.curseforge.com/minecraft/mc-mods/cherry-on-1-12-2" + "\n"
                    + "--------------------------------------------------" + "\n"
            ;
        }
    }
}